version: 2
updates:
  - package-ecosystem: "pub"
    directory: "package/inject_compile"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "package/inject_compile_generator"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "example/train"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "example/clean_architecture"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "example/coffee"
    schedule:
      interval: "daily"
